### ISSUE TITLE
Unable to delete Seasons / Competitors

### ISSUE THREAD

**Issue by natrad100** [jbfraser1/SailScores#127]
- click **delete** button (https://www.sailscores.com/ASSATEST/Season/Delete/25abfce1-c2f0-4247-b303-21cc42b57a9c)

- Click Delete

-> Information disappears from the page (as if there is no info in the database, but when you enter the admin panel it remains. season remains in the database

**Comment by jbfraser1** [comment]
I haven't tried to reproduce yet: I suspect these weren't deleting because they were connected to other things. The season may have been connected to a series, and the competitors may have been connected to races, with results.

If that's the case, then the answer will be to have an alert blocking the delete attempt, and maybe links/list of connected things that are blocking this.

I did just confirm that a newly created season can be deleted and a newly created competitor can be deleted, so the connections to other things seems to be the likely problem.

Returning informative errors on failed operations is definitely an area that needs improvement.
